language: go
go_import_path: $GOPATH/src/github.com/anemiq
before_script:
  - go vet ./...
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
