[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/graphql-go/graphql"
  version = "0.7.4"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
